version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - node-app

  node-app:
    environment:
      - PORT=3000
    depends_on: 
      - mongo
  
  mongo:
    image: mongo 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aiman
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    
    # /data/db inside the container, where MongoDB by default will write its data files.
    # we are using named volume named "mongo-db"
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:

