version: "3"
services:
  nginx:
    ports:
      - "80:80"


  react-app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_HOMEPAGE_PRODUCT_HEADING=Latest Products #not passed as env variable because of multi stage build. It will not work

  node-app:
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
    build: 
      args:
        IMAGE_ENV: production
    image: aimanzaheb/ecom-api-docker
    environment: 
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
    command: node src/server.js
  
  mongo:
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}