version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build: 
      context: ./
      args:
        NODE_ENV: production
    image: aimanzaheb/ecom-api-docker
    environment: 
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
    command: node backend/server.js
  
  mongo:
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}